# Generated by Django 5.1.1 on 2025-02-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('house_name', models.CharField(db_index=True, max_length=100)),
                ('jiaoshui_name', models.CharField(db_index=True, max_length=20)),
                ('fee', models.CharField(max_length=20)),
                ('zhongjie_name', models.CharField(db_index=True, max_length=20)),
                ('jiaoyi_at', models.DateTimeField(db_index=True)),
                ('fangchanzheng_images', models.CharField(max_length=1000)),
                ('shuipiao_images', models.CharField(max_length=1000)),
                ('tongzhishu_images', models.CharField(max_length=1000)),
                ('buyer_name', models.CharField(db_index=True, max_length=20)),
                ('buyer_phone_number', models.CharField(db_index=True, max_length=20)),
                ('buyer_id', models.CharField(db_index=True, max_length=30)),
                ('buyer_hukou_images', models.CharField(max_length=1000)),
                ('buyer_id_images', models.CharField(max_length=1000)),
                ('buyer_marriage_images', models.CharField(max_length=1000)),
                ('seller_name', models.CharField(db_index=True, max_length=20)),
                ('seller_phone_number', models.CharField(db_index=True, max_length=20)),
                ('seller_id', models.CharField(db_index=True, max_length=30)),
                ('seller_hukou_images', models.CharField(max_length=1000)),
                ('seller_id_images', models.CharField(max_length=1000)),
                ('seller_marriage_images', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'house',
            },
        ),
    ]
