# Generated by Django 5.1.1 on 2025-03-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='chengban_name',
            field=models.CharField(db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='remark',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='house',
            name='wangqianhetong_images',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
